name: aaravian-llm-benchmark
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip>=24.2
  - jupyterlab=4.2.5
  - ipykernel=6.29.5
  - numpy=2.1.2
  - pandas=2.2.3
  - pyyaml=6.0.2
  - plotly=5.24.0
  - pip:
      - kaleido==0.2.1
      - httpx==0.27.2
      - python-dotenv==1.0.1
      - jinja2==3.1.4
      - retrying==1.3.4
      - openai==1.51.2
      - cohere==5.10.0
      - tiktoken==0.7.0
      - neo4j==5.25.0
      - qdrant-client==1.10.1
      - ragas==0.1.9
      - llama-index==0.11.11
      - llama-index-llms-openai==0.2.11
      - llama-index-embeddings-openai==0.2.5
      - llama-index-vector-stores-qdrant==0.8.6
      - llama-index-postprocessor-cohere-rerank==0.2.0
      - rank-bm25==0.2.2

